export const CREATE_RESTAURANT_REQUEST="CREATE_RESTURANT_REQUEST";
export const CREATE_RESTAURANT_SUCCESS="CREATE_RESTURANT_SUCCESS";
export const CREATE_RESTAURANT_FAILURE="CREATE_RESTURANT_FAILURE";

export const GET_ALL_RESTAURANTS_REQUEST="GET_ALL_RESTURANTS_REQUEST";
export const GET_ALL_RESTAURANTS_SUCCESS="GET_ALL_RESTURANTS_SUCCESS";
export const GET_ALL_RESTAURANTS_FAILURE="GET_ALL_RESTURANTS_FAILURE";

export const DELETE_RESTAURANT_REQUEST="DELETE_RESTURANT_REQUEST";
export const DELETE_RESTAURANT_SUCCESS="DELETE_RESTURANT_SUCCESS";
export const DELETE_RESTAURANT_FAILURE="DELETE_RESTURANT_FAILURE";

export const UPDATE_RESTAURANT_REQUEST="UPDATE_RESTURANT_REQUEST";
export const UPDATE_RESTAURANT_SUCCESS="UPDATE_RESTURANT_SUCCESS";
export const UPDATE_RESTAURANT_FAILURE="UPDATE_RESTURANT_FAILURE";

export const GET_RESTAURANT_BY_ID_REQUEST="GET_RESTURANT_BY_ID_REQUEST";
export const GET_RESTAURANT_BY_ID_SUCCESS="GET_RESTURANT_BY_ID_SUCCESS";
export const GET_RESTAURANT_BY_ID_FAILURE="GET_RESTURANT_BY_ID_FAILURE";

export const GET_RESTAURANT_BY_USER_ID_REQUEST="GET_RESTURANT_BY_USER_ID_REQUEST";
export const GET_RESTAURANT_BY_USER_ID_SUCCESS="GET_RESTURANT_BY_USER_ID_REQUEST";
export const GET_RESTAURANT_BY_USER_ID_FAILURE="GET_RESTURANT_BY_USER_ID_FAILURE";


export const CREATE_EVENTS_REQUEST="CREATE_EVENTS_REQUEST";
export const CREATE_EVENTS_SUCCESS="CREATE_EVENTS_SUCCESS";
export const CREATE_EVENTS_FAILURE="CREATE_EVENTS_FAILURE";

export const GET_ALL_EVENTS_REQUEST="GET_ALL_EVENTS_REQUEST";
export const GET_ALL_EVENTS_SUCCESS="GET_ALL_EVENTS_SUCCESS";
export const GET_ALL_EVENTS_FAILURE="GET_ALL_EVENTS_FAILURE";

export const DELETE_EVENTS_REQUEST="DELETE_EVENTS_REQUEST";
export const DELETE_EVENTS_SUCCESS="DELETE_EVENTS_SUCCESS";
export const DELETE_EVENTS_FAILURE="DELETE_EVENTS_FAILURE";

export const GET_RESTAURANTS_EVENTS_REQUEST="GET_RESTURANTS_EVENTS_REQUEST";
export const GET_RESTAURANTS_EVENTS_SUCCESS="GET_RESTURANTS_EVENTS_SUCCESS";
export const GET_RESTAURANTS_EVENTS_FAILURE="GET_RESTURANTS_EVENTS_FAILURE";

export const CREATE_CATEGORY_REQUEST="CREATE_CATEGORY_REQUEST";
export const CREATE_CATEGORY_SUCCESS="CREATE_CATEGORY_SUCCESS";
export const CREATE_CATEGORY_FAILURE="CREATE_CATEGORY_FAILURE";
 
export const GET_RESTAURANTS_CATEGORY_REQUEST="GET_RESTAURANTS_CATEGORY_REQUEST";
export const GET_RESTAURANTS_CATEGORY_SUCCESS="GET_RESTAURANTS_CATEGORY_SUCCESS";
export const GET_RESTAURANTS_CATEGORY_FAILURE="GET_RESTAURANTS_CATEGORY_FAILURE";