export const REGISTER_REQUEST="REGISTER_REQUEST";
export const REGISTER_SUCCESS="REGISTER_REQUEST";
export const REGISTER_FAILURE="REGISTER_REQUEST";


export const LOGIN_REQUEST="REGISTER_REQUEST";
export const LOGIN_SUCCESS="REGISTER_REQUEST";
export const LOGIN_FAILURE="REGISTER_REQUEST";

export const  GET_USER_REQUEST="REGISTER_REQUEST";
export const  GET_USER_SUCCESS="REGISTER_REQUEST";
export const  GET_USER_FAILURE="REGISTER_REQUEST";

export const ADD_TO_FAVORITE_REQUEST="REGISTER_REQUEST";
export const ADD_TO_FAVORITE_SUCCESS="REGISTER_REQUEST";
export const ADD_TO_FAVORITE_FAILURE="REGISTER_REQUEST";

export const LOGOUT="LOGOUT";   

